// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"

// ExchangeService is an autogenerated mock type for the ExchangeService type
type ExchangeService struct {
	mock.Mock
}

// GetConversionRates provides a mock function with given fields: ctx, from, to
func (_m *ExchangeService) GetConversionRates(ctx context.Context, from string, to []string) (map[string]float64, error) {
	ret := _m.Called(ctx, from, to)

	var r0 map[string]float64
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) map[string]float64); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
