// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"

import mock "github.com/stretchr/testify/mock"
import model "github.com/dexterorion/smartmei/model"

// StartMeiService is an autogenerated mock type for the StartMeiService type
type StartMeiService struct {
	mock.Mock
}

// CrawData provides a mock function with given fields: ctx, url
func (_m *StartMeiService) CrawData(ctx context.Context, url string) (*model.DescriptionValueData, error) {
	ret := _m.Called(ctx, url)

	var r0 *model.DescriptionValueData
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.DescriptionValueData); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DescriptionValueData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
